### ISSUE TITLE
Need model, training data

### ISSUE THREAD

**Issue by Sonu2396** [MuhammadWaqar621/Smart-Meter-Reading#2]
Hi, please provide training data and model. Also instructions. It's not available on the main repo.

**Comment by MuhammadWaqar621** [comment]
I'll update the repo and readme file for full guide.

**Comment by Sonu2396** [comment]
Thanks. Can I have your email address?

**Comment by MuhammadWaqar621** [comment]
waqarsahi621@gmail.com

**Comment by MuhammadWaqar621** [comment]
I'm not able to share dataset due to confidentiality
