### ISSUE TITLE
模型下载地址不存在

### ISSUE THREAD

**Issue by fangsanyong** [MuhammadWaqar621/Smart-Meter-Reading#3]
您好，模型的下载地址不存在，方便提供一下新的有效地址吗

**Comment by fangsanyong** [comment]
Sorry, the file you have requested does not exist.

Make sure that you have the correct URL and the file exists.

Get stuff done with Google Drive

Apps in Google Drive make it easy to create, store and share online documents, spreadsheets, presentations and more.

Learn more at [drive.google.com/start/apps](https://drive.google.com/start/apps).

**Comment by MuhammadWaqar621** [comment]
https://drive.google.com/file/d/1TIZLHDfS5gAYhpLNYosTrEnTiUmuSmXc/view?usp=sharing
