### ISSUE TITLE
datasets and weights

### ISSUE THREAD

**Issue by fangsanyong** [MuhammadWaqar621/Smart-Meter-Reading#4]
couly you give me a piece of datasets and weights. the link in code is invaild

**Comment by MuhammadWaqar621** [comment]
dataset is confidential, model weights already shared.
https://drive.google.com/drive/folders/1YKIA29tCSprDncX62JeZgO0guUSZwNgl?usp=sharing

**Comment by fangsanyong** [comment]
I have got it ,thank you very much.

**Comment by fangsanyong** [comment]
> I have got it ,thank you very much.

sorry i have got it in  #3 link.
